-- Crear tablas
CREATE TABLE TBL_PERSONAS (
    CODIGO_PERSONA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    CORREO VARCHAR2(100),
    FECHA_NACIMIENTO TIMESTAMP
);

CREATE TABLE TBL_USUARIOS (
    CODIGO_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PERSONA NUMBER,
    CONSTRAINT fk_usuario_persona FOREIGN KEY (CODIGO_PERSONA) REFERENCES TBL_PERSONAS(CODIGO_PERSONA)
);

CREATE TABLE TBL_ARTISTAS (
    CODIGO_ARTISTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ARTISTICO VARCHAR2(50),
    CODIGO_PERSONA NUMBER,
    CODIGO_DISQUERA NUMBER,
    CONSTRAINT fk_artista_persona FOREIGN KEY (CODIGO_PERSONA) REFERENCES TBL_PERSONAS(CODIGO_PERSONA),
    CONSTRAINT fk_artista_disquera FOREIGN KEY (CODIGO_DISQUERA) REFERENCES TBL_DISQUERAS(CODIGO_DISQUERA)
);

CREATE TABLE TBL_PODCASTERS (
    CODIGO_PODCASTER NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PERSONA NUMBER,
    CONSTRAINT fk_podcaster_persona FOREIGN KEY (CODIGO_PERSONA) REFERENCES TBL_PERSONAS(CODIGO_PERSONA)
);

CREATE TABLE TBL_BIBLIOTECA (
    CODIGO_BIBLIOTECA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_USUARIO NUMBER,
    CODIGO_PLAYLIST NUMBER,
    CODIGO_ALBUM NUMBER,
    CODIGO_ARTISTA NUMBER,
    CONSTRAINT fk_biblioteca_usuario FOREIGN KEY (CODIGO_USUARIO) REFERENCES TBL_USUARIOS(CODIGO_USUARIO),
    CONSTRAINT fk_biblioteca_playlist FOREIGN KEY (CODIGO_PLAYLIST) REFERENCES TBL_PLAYLISTS(CODIGO_PLAYLIST),
    CONSTRAINT fk_biblioteca_album FOREIGN KEY (CODIGO_ALBUM) REFERENCES TBL_ALBUMES(CODIGO_ALBUM),
    CONSTRAINT fk_biblioteca_artista FOREIGN KEY (CODIGO_ARTISTA) REFERENCES TBL_ARTISTAS(CODIGO_ARTISTA)
);

CREATE TABLE TBL_DISQUERAS (
    CODIGO_DISQUERA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_DISQUERA VARCHAR2(100),
    DESCRIPCION_DISQUERA VARCHAR2(255)
);

CREATE TABLE TBL_PODCASTS (
    CODIGO_PODCAST NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_PODCAST VARCHAR2(100),
    DURACION_PODCAST INTERVAL DAY TO SECOND,
    CODIGO_PODCASTER NUMBER,
    CONSTRAINT fk_podcast_podcaster FOREIGN KEY (CODIGO_PODCASTER) REFERENCES TBL_PODCASTERS(CODIGO_PODCASTER)
);

CREATE TABLE TBL_ALBUMES (
    CODIGO_ALBUM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ALBUM VARCHAR2(100),
    FECHA_PUBLICACION TIMESTAMP,
    CODIGO_ARTISTA NUMBER,
    CODIGO_TIPO_ALBUM NUMBER,
    CONSTRAINT fk_album_artista FOREIGN KEY (CODIGO_ARTISTA) REFERENCES TBL_ARTISTAS(CODIGO_ARTISTA),
    CONSTRAINT fk_album_tipo FOREIGN KEY (CODIGO_TIPO_ALBUM) REFERENCES TBL_TIPO_ALBUMES(CODIGO_TIPO_ALBUM)
);

CREATE TABLE TBL_CATEGORIA_PODCASTS (
    CODIGO_CATEGORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PODCAST NUMBER,
    CONSTRAINT fk_categoria_podcast FOREIGN KEY (CODIGO_PODCAST) REFERENCES TBL_PODCASTS(CODIGO_PODCAST)
);

CREATE TABLE TBL_TIPO_ALBUMES (
    CODIGO_TIPO_ALBUM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_TIPO_ALBUM VARCHAR2(50)
);

CREATE TABLE TBL_CANCIONES (
    CODIGO_CANCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_CANCION VARCHAR2(100),
    DURACION INTERVAL DAY TO SECOND,
    CODIGO_ALBUM NUMBER,
    CODIGO_GENERO NUMBER,
    CONSTRAINT fk_cancion_album FOREIGN KEY (CODIGO_ALBUM) REFERENCES TBL_ALBUMES(CODIGO_ALBUM),
    CONSTRAINT fk_cancion_genero FOREIGN KEY (CODIGO_GENERO) REFERENCES TBL_GENERO(CODIGO_GENERO)
);

CREATE TABLE TBL_PLAYLISTS (
    CODIGO_PLAYLIST NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_PLAYLIST VARCHAR2(100)
);

CREATE TABLE TBL_CANCIONES_PLAYLIST (
    CODIGO_CANCIONES_PLAYLIST NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CANCION NUMBER,
    CODIGO_PLAYLIST NUMBER,
    CONSTRAINT fk_canciones_playlist_cancion FOREIGN KEY (CODIGO_CANCION) REFERENCES TBL_CANCIONES(CODIGO_CANCION),
    CONSTRAINT fk_canciones_playlist_playlist FOREIGN KEY (CODIGO_PLAYLIST) REFERENCES TBL_PLAYLISTS(CODIGO_PLAYLIST)
);

CREATE TABLE TBL_GENERO (
    CODIGO_GENERO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_GENERO VARCHAR2(50),
    DESCRIPCION_GENERO VARCHAR2(255)
);
