-- Insertar datos en TBL_PERSONAS
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Juan', 'Pérez', 'juan.perez@email.com', TO_TIMESTAMP('1990-05-15', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Ana', 'López', 'ana.lopez@email.com', TO_TIMESTAMP('1985-08-20', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Carlos', 'García', 'carlos.garcia@email.com', TO_TIMESTAMP('1995-03-10', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Laura', 'Martínez', 'laura.martinez@email.com', TO_TIMESTAMP('2000-12-05', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Pedro', 'Pérez', 'juan.perez@email.com', TO_TIMESTAMP('1990-05-15', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Lana', 'López', 'ana.lopez@email.com', TO_TIMESTAMP('1985-08-20', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Carmelito', 'García', 'carlos.garcia@email.com', TO_TIMESTAMP('1995-03-10', 'YYYY-MM-DD'));
  INSERT INTO TBL_PERSONAS (NOMBRE, APELLIDO, CORREO, FECHA_NACIMIENTO) VALUES 
      ('Laura', 'Marano', 'laura.marano@email.com', TO_TIMESTAMP('2000-12-05', 'YYYY-MM-DD'));

  -- Insertar datos en TBL_USUARIOS
  INSERT INTO TBL_USUARIOS (CODIGO_PERSONA) VALUES (13);
  INSERT INTO TBL_USUARIOS (CODIGO_PERSONA) VALUES (14);
  INSERT INTO TBL_USUARIOS (CODIGO_PERSONA) VALUES (15);
  INSERT INTO TBL_USUARIOS (CODIGO_PERSONA) VALUES (16);

  -- Insertar datos en TBL_ARTISTAS
  INSERT INTO TBL_ARTISTAS (NOMBRE_ARTISTICO, CODIGO_PERSONA, CODIGO_DISQUERA) VALUES 
      ('Artista1', 22, 4);
  INSERT INTO TBL_ARTISTAS (NOMBRE_ARTISTICO, CODIGO_PERSONA, CODIGO_DISQUERA) VALUES 
      ('Artista2', 23, 2);
  INSERT INTO TBL_ARTISTAS (NOMBRE_ARTISTICO, CODIGO_PERSONA, CODIGO_DISQUERA) VALUES 
      ('Artista3', 24, 5);
  INSERT INTO TBL_ARTISTAS (NOMBRE_ARTISTICO, CODIGO_PERSONA, CODIGO_DISQUERA) VALUES 
      ('Artista4', 21, 3);

  -- Insertar datos en TBL_PODCASTERS
  INSERT INTO TBL_PODCASTERS (CODIGO_PERSONA) VALUES (22);
  INSERT INTO TBL_PODCASTERS (CODIGO_PERSONA) VALUES (23);
  INSERT INTO TBL_PODCASTERS (CODIGO_PERSONA) VALUES (13);
  INSERT INTO TBL_PODCASTERS (CODIGO_PERSONA) VALUES (16);

  -- Insertar datos en TBL_BIBLIOTECA
  INSERT INTO TBL_BIBLIOTECA (CODIGO_USUARIO, CODIGO_PLAYLIST, CODIGO_ALBUM, CODIGO_ARTISTA) VALUES (31, 2, 22, 24);
  INSERT INTO TBL_BIBLIOTECA (CODIGO_USUARIO, CODIGO_PLAYLIST, CODIGO_ALBUM, CODIGO_ARTISTA) VALUES (32, 3, 23, 25);
  INSERT INTO TBL_BIBLIOTECA (CODIGO_USUARIO, CODIGO_PLAYLIST, CODIGO_ALBUM, CODIGO_ARTISTA) VALUES (33, 4, 24, 25);
  INSERT INTO TBL_BIBLIOTECA (CODIGO_USUARIO, CODIGO_PLAYLIST, CODIGO_ALBUM, CODIGO_ARTISTA) VALUES (34, 5, 25, 27);

  -- Insertar datos en TBL_DISQUERAS
  INSERT INTO TBL_DISQUERAS (NOMBRE_DISQUERA, DESCRIPCION_DISQUERA) VALUES ('Discográfica1', 'Descripción de la discográfica 1');
  INSERT INTO TBL_DISQUERAS (NOMBRE_DISQUERA, DESCRIPCION_DISQUERA) VALUES ('Discográfica2', 'Descripción de la discográfica 2');
  INSERT INTO TBL_DISQUERAS (NOMBRE_DISQUERA, DESCRIPCION_DISQUERA) VALUES ('Discográfica3', 'Descripción de la discográfica 3');
  INSERT INTO TBL_DISQUERAS (NOMBRE_DISQUERA, DESCRIPCION_DISQUERA) VALUES ('Discográfica4', 'Descripción de la discográfica 4');

  -- Insertar datos en TBL_PODCASTS
  INSERT INTO TBL_PODCASTS (NOMBRE_PODCAST, DURACION_PODCAST, CODIGO_PODCASTER) VALUES ('Podcast1', INTERVAL '30' MINUTE, 22);
  INSERT INTO TBL_PODCASTS (NOMBRE_PODCAST, DURACION_PODCAST, CODIGO_PODCASTER) VALUES ('Podcast2', INTERVAL '45' MINUTE, 23);
  INSERT INTO TBL_PODCASTS (NOMBRE_PODCAST, DURACION_PODCAST, CODIGO_PODCASTER) VALUES ('Podcast3', INTERVAL '20' MINUTE, 24);
  INSERT INTO TBL_PODCASTS (NOMBRE_PODCAST, DURACION_PODCAST, CODIGO_PODCASTER) VALUES ('Podcast4', INTERVAL '60' MINUTE, 25);

  -- Insertar datos en TBL_ALBUMES
  INSERT INTO TBL_ALBUMES (NOMBRE_ALBUM, FECHA_PUBLICACION, CODIGO_ARTISTA, CODIGO_TIPO_ALBUM) VALUES ('Álbum1', TO_TIMESTAMP('2022-01-01', 'YYYY-MM-DD'), 24, 2);
  INSERT INTO TBL_ALBUMES (NOMBRE_ALBUM, FECHA_PUBLICACION, CODIGO_ARTISTA, CODIGO_TIPO_ALBUM) VALUES ('Álbum2', TO_TIMESTAMP('2022-05-15', 'YYYY-MM-DD'), 25, 3);
  INSERT INTO TBL_ALBUMES (NOMBRE_ALBUM, FECHA_PUBLICACION, CODIGO_ARTISTA, CODIGO_TIPO_ALBUM) VALUES ('Álbum3', TO_TIMESTAMP('2021-11-02', 'YYYY-MM-DD'), 26, 4);
  INSERT INTO TBL_ALBUMES (NOMBRE_ALBUM, FECHA_PUBLICACION, CODIGO_ARTISTA, CODIGO_TIPO_ALBUM) VALUES ('Álbum4', TO_TIMESTAMP('2023-02-28', 'YYYY-MM-DD'), 27, 5);

  -- Insertar datos en TBL_CATEGORIA_PODCASTS
  INSERT INTO TBL_CATEGORIA_PODCASTS (CODIGO_PODCAST) VALUES (22);
  INSERT INTO TBL_CATEGORIA_PODCASTS (CODIGO_PODCAST) VALUES (23);
  INSERT INTO TBL_CATEGORIA_PODCASTS (CODIGO_PODCAST) VALUES (24);
  INSERT INTO TBL_CATEGORIA_PODCASTS (CODIGO_PODCAST) VALUES (25);

  -- Insertar datos en TBL_TIPO_ALBUMES
  INSERT INTO TBL_TIPO_ALBUMES (NOMBRE_TIPO_ALBUM) VALUES ('Sencillo');
  INSERT INTO TBL_TIPO_ALBUMES (NOMBRE_TIPO_ALBUM) VALUES ('EP');
  INSERT INTO TBL_TIPO_ALBUMES (NOMBRE_TIPO_ALBUM) VALUES ('Álbum');
  INSERT INTO TBL_TIPO_ALBUMES (NOMBRE_TIPO_ALBUM) VALUES ('Colaboración');

  -- Insertar datos en TBL_CANCIONES
  INSERT INTO TBL_CANCIONES (NOMBRE_CANCION, DURACION, CODIGO_ALBUM, CODIGO_GENERO) VALUES ('Canción1', INTERVAL '4' MINUTE, 22, 2);
  INSERT INTO TBL_CANCIONES (NOMBRE_CANCION, DURACION, CODIGO_ALBUM, CODIGO_GENERO) VALUES ('Canción2', INTERVAL '3' MINUTE, 23, 3);
  INSERT INTO TBL_CANCIONES (NOMBRE_CANCION, DURACION, CODIGO_ALBUM, CODIGO_GENERO) VALUES ('Canción3', INTERVAL '5' MINUTE, 24, 4);
  INSERT INTO TBL_CANCIONES (NOMBRE_CANCION, DURACION, CODIGO_ALBUM, CODIGO_GENERO) VALUES ('Canción4', INTERVAL '4' MINUTE, 25, 5);

  -- Insertar datos en TBL_PLAYLISTS
  INSERT INTO TBL_PLAYLISTS (NOMBRE_PLAYLIST) VALUES ('Playlist1');
  INSERT INTO TBL_PLAYLISTS (NOMBRE_PLAYLIST) VALUES ('Playlist2');
  INSERT INTO TBL_PLAYLISTS (NOMBRE_PLAYLIST) VALUES ('Playlist3');
  INSERT INTO TBL_PLAYLISTS (NOMBRE_PLAYLIST) VALUES ('Playlist4');

  -- Insertar datos en TBL_CANCIONES_PLAYLIST
  INSERT INTO TBL_CANCIONES_PLAYLIST (CODIGO_CANCION, CODIGO_PLAYLIST) VALUES (1, 1);
  INSERT INTO TBL_CANCIONES_PLAYLIST (CODIGO_CANCION, CODIGO_PLAYLIST) VALUES (2, 2);
  INSERT INTO TBL_CANCIONES_PLAYLIST (CODIGO_CANCION, CODIGO_PLAYLIST) VALUES (3, 3);
  INSERT INTO TBL_CANCIONES_PLAYLIST (CODIGO_CANCION, CODIGO_PLAYLIST) VALUES (4, 4);

  -- Insertar datos en TBL_GENERO
  INSERT INTO TBL_GENERO (NOMBRE_GENERO, DESCRIPCION_GENERO) VALUES ('Género1', 'Descripción del género 1');
  INSERT INTO TBL_GENERO (NOMBRE_GENERO, DESCRIPCION_GENERO) VALUES ('Género2', 'Descripción del género 2');
  INSERT INTO TBL_GENERO (NOMBRE_GENERO, DESCRIPCION_GENERO) VALUES ('Género3', 'Descripción del género 3');
  INSERT INTO TBL_GENERO (NOMBRE_GENERO, DESCRIPCION_GENERO) VALUES ('Género4', 'Descripción del género 4');