CREATE USER C##usuariospotify
IDENTIFIED BY 1234
DEFAULT TABLESPACE users

GRANT CREATE ANY TABLE TO C##usuariospotify WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO C##usuariospotify WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO C##usuariospotify WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO C##usuariospotify WITH ADMIN OPTION;